#!/bin/sh
#
# Add the upstream repositories as a remotes

cd glib
git remote add upstream "git://git.gnome.org/glib"
cd ..

for path in gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad; do
    cd $path
    git remote add upstream "git://anongit.freedesktop.org/gstreamer/$path"
    cd ..
done

cd libvpx
git remote add upstream "http://git.chromium.org/webm/libvpx.git"
cd ..
